processmaker:
  build: .
  ports:
    - "8091:80"
    - "8092:8080"
  expose:
    - "9000"
  volumes:
    - processmaker:/opt/processmaker
  links:
    - mysql:mysql
mysql:
  image: mysql:5.6.24
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "sample"
